/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omicron.view;

import Others.IDGenerator;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeArray;
import omicron.controller.BrandController;
import omicron.controller.CustomerController;
import omicron.model.Brand;
import omicron.model.Customer;

/**
 *
 * @author Dulan
 */
public class BrandManagement extends javax.swing.JFrame {

    int timeRun = 0;

    /**
     * Creates new form CustomerManagement
     */
    public BrandManagement() {
        initComponents();
        getclock();
        bmAddLabelUpdateOrDelete.setVisible(false);
        showAllCustomers();
        bmAddText_CustomerId.setEditable(false);
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        loadBrandId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        homeIconPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mainButtonPanel = new javax.swing.JPanel();
        closeButtonLabel = new javax.swing.JLabel();
        minimizeButtonLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bmAddTabel_View = new javax.swing.JTable();
        cmCustDetailPanel = new javax.swing.JPanel();
        cmAddPanell_Main = new javax.swing.JPanel();
        cmAddLabel_Main = new javax.swing.JLabel();
        cmAddPanel_GetDetail = new javax.swing.JPanel();
        cmAddLabel_CustId = new javax.swing.JLabel();
        bmAddText_CustomerId = new javax.swing.JTextField();
        cmAddLabel_CustName = new javax.swing.JLabel();
        bmAddText_CustomerName = new javax.swing.JTextField();
        bmAddLabelUpdateOrDelete = new javax.swing.JLabel();
        cmCustMaintaimPanel = new javax.swing.JPanel();
        bmLabel_AddCustomer = new javax.swing.JLabel();
        bmLabel_DeleteCustomer = new javax.swing.JLabel();
        bmLabel_SearchCustomer = new javax.swing.JLabel();
        bmLabel_UpdateCustomer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateTimePanel = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MainLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setOpaque(false);

        homeLabel.setFont(new java.awt.Font("Lucida Bright", 3, 85)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 205, 200));
        homeLabel.setText("  O");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 130));

        homeIconPanel.setOpaque(false);

        javax.swing.GroupLayout homeIconPanelLayout = new javax.swing.GroupLayout(homeIconPanel);
        homeIconPanel.setLayout(homeIconPanelLayout);
        homeIconPanelLayout.setHorizontalGroup(
            homeIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        homeIconPanelLayout.setVerticalGroup(
            homeIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(homeIconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 560));

        titlePanel.setOpaque(false);

        titleLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setText("Item Management...");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 510, 50));

        mainButtonPanel.setOpaque(false);

        closeButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omicron.images/close_64.png"))); // NOI18N
        closeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseClicked(evt);
            }
        });

        minimizeButtonLabel.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\minimize_64.png")); // NOI18N
        minimizeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainButtonPanelLayout = new javax.swing.GroupLayout(mainButtonPanel);
        mainButtonPanel.setLayout(mainButtonPanelLayout);
        mainButtonPanelLayout.setHorizontalGroup(
            mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainButtonPanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(minimizeButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainButtonPanelLayout.setVerticalGroup(
            mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainButtonPanelLayout.createSequentialGroup()
                .addGroup(mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 130, -1));

        tablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), null, null));
        tablePanel.setOpaque(false);

        bmAddTabel_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bmAddTabel_View.setOpaque(false);
        jScrollPane1.setViewportView(bmAddTabel_View);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        getContentPane().add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 590, 330));

        cmCustDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmCustDetailPanel.setOpaque(false);
        cmCustDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmAddPanell_Main.setBackground(new java.awt.Color(255, 0, 153));
        cmAddPanell_Main.setOpaque(false);

        cmAddLabel_Main.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        cmAddLabel_Main.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_Main.setText("Item Details");

        javax.swing.GroupLayout cmAddPanell_MainLayout = new javax.swing.GroupLayout(cmAddPanell_Main);
        cmAddPanell_Main.setLayout(cmAddPanell_MainLayout);
        cmAddPanell_MainLayout.setHorizontalGroup(
            cmAddPanell_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanell_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmAddLabel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        cmAddPanell_MainLayout.setVerticalGroup(
            cmAddPanell_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmAddLabel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        cmCustDetailPanel.add(cmAddPanell_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        cmAddPanel_GetDetail.setOpaque(false);

        cmAddLabel_CustId.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cmAddLabel_CustId.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustId.setText("Item ID");

        bmAddText_CustomerId.setBackground(new java.awt.Color(204, 204, 204));
        bmAddText_CustomerId.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bmAddText_CustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmAddText_CustomerIdActionPerformed(evt);
            }
        });

        cmAddLabel_CustName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cmAddLabel_CustName.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustName.setText("Item Name");

        bmAddText_CustomerName.setBackground(new java.awt.Color(204, 204, 204));
        bmAddText_CustomerName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bmAddText_CustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmAddText_CustomerNameActionPerformed(evt);
            }
        });

        bmAddLabelUpdateOrDelete.setBackground(new java.awt.Color(0, 165, 255));
        bmAddLabelUpdateOrDelete.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        bmAddLabelUpdateOrDelete.setForeground(new java.awt.Color(255, 255, 255));
        bmAddLabelUpdateOrDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bmAddLabelUpdateOrDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bmAddLabelUpdateOrDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmAddLabelUpdateOrDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cmAddPanel_GetDetailLayout = new javax.swing.GroupLayout(cmAddPanel_GetDetail);
        cmAddPanel_GetDetail.setLayout(cmAddPanel_GetDetailLayout);
        cmAddPanel_GetDetailLayout.setHorizontalGroup(
            cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addComponent(cmAddLabel_CustId, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bmAddText_CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addComponent(cmAddLabel_CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bmAddText_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(bmAddLabelUpdateOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cmAddPanel_GetDetailLayout.setVerticalGroup(
            cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bmAddText_CustomerId, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cmAddLabel_CustId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bmAddText_CustomerName)
                    .addComponent(cmAddLabel_CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(bmAddLabelUpdateOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cmCustDetailPanel.add(cmAddPanel_GetDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 250));

        getContentPane().add(cmCustDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 470, 320));

        cmCustMaintaimPanel.setOpaque(false);

        bmLabel_AddCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\itemAdd.png")); // NOI18N
        bmLabel_AddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmLabel_AddCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bmLabel_AddCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bmLabel_AddCustomerMouseExited(evt);
            }
        });

        bmLabel_DeleteCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\itemRemove.png")); // NOI18N
        bmLabel_DeleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmLabel_DeleteCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bmLabel_DeleteCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bmLabel_DeleteCustomerMouseExited(evt);
            }
        });

        bmLabel_SearchCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\itemSerch.png")); // NOI18N
        bmLabel_SearchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmLabel_SearchCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bmLabel_SearchCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bmLabel_SearchCustomerMouseExited(evt);
            }
        });

        bmLabel_UpdateCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\itemUpdate.png")); // NOI18N
        bmLabel_UpdateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmLabel_UpdateCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bmLabel_UpdateCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bmLabel_UpdateCustomerMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delete");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout cmCustMaintaimPanelLayout = new javax.swing.GroupLayout(cmCustMaintaimPanel);
        cmCustMaintaimPanel.setLayout(cmCustMaintaimPanelLayout);
        cmCustMaintaimPanelLayout.setHorizontalGroup(
            cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addGroup(cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bmLabel_AddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bmLabel_DeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bmLabel_SearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bmLabel_UpdateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addGroup(cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cmCustMaintaimPanelLayout.setVerticalGroup(
            cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addComponent(bmLabel_AddCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bmLabel_SearchCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bmLabel_DeleteCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(bmLabel_UpdateCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        getContentPane().add(cmCustMaintaimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 180, 90, 550));

        dateTimePanel.setOpaque(false);

        clock.setFont(new java.awt.Font("DS-Digital", 0, 60)); // NOI18N
        clock.setForeground(new java.awt.Color(0, 165, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clock.setText("2:13:15  PM");

        javax.swing.GroupLayout dateTimePanelLayout = new javax.swing.GroupLayout(dateTimePanel);
        dateTimePanel.setLayout(dateTimePanelLayout);
        dateTimePanelLayout.setHorizontalGroup(
            dateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateTimePanelLayout.createSequentialGroup()
                .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        dateTimePanelLayout.setVerticalGroup(
            dateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(dateTimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 310, 60));

        jButton1.setFont(new java.awt.Font("Miriam Fixed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 690, 140, 40));

        MainLable.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\final.jpg")); // NOI18N
        MainLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(MainLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonLabelMouseClicked

    private void bmAddText_CustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmAddText_CustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmAddText_CustomerIdActionPerformed

    private void bmAddText_CustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmAddText_CustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmAddText_CustomerNameActionPerformed

    private void bmLabel_AddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_AddCustomerMouseClicked
        setClearAll();
        loadBrandId();
        bmAddLabelUpdateOrDelete.setText("Add");
        bmAddLabelUpdateOrDelete.setVisible(true);

    }//GEN-LAST:event_bmLabel_AddCustomerMouseClicked

    private void bmLabel_SearchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_SearchCustomerMouseClicked
        setClearAll();
        bmAddLabelUpdateOrDelete.setText("OK");
        bmAddLabelUpdateOrDelete.setVisible(true);
        searchBrand();
    }//GEN-LAST:event_bmLabel_SearchCustomerMouseClicked

    private void bmLabel_UpdateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_UpdateCustomerMouseClicked
        setClearAll();
        bmAddLabelUpdateOrDelete.setText("Update");
        bmAddLabelUpdateOrDelete.setVisible(true);
        searchBrand();
    }//GEN-LAST:event_bmLabel_UpdateCustomerMouseClicked

    private void bmLabel_DeleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_DeleteCustomerMouseClicked
        setClearAll();
        bmAddLabelUpdateOrDelete.setText("Delete");
        bmAddLabelUpdateOrDelete.setVisible(true);
        searchBrand();
    }//GEN-LAST:event_bmLabel_DeleteCustomerMouseClicked

    private void bmAddLabelUpdateOrDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmAddLabelUpdateOrDeleteMouseClicked
        String text = bmAddLabelUpdateOrDelete.getText();
        if (text.equals("Update")) {

            modifyInBrandTable();

        } else if (text.equals("Delete")) {

            removeFromBrandTable();

        } else if (text.equals("Add")) {

            intoBrandTable();

        }
        setClearAll();
        showAllCustomers();
        loadBrandId();
    }//GEN-LAST:event_bmAddLabelUpdateOrDeleteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bmLabel_AddCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_AddCustomerMouseEntered
        jLabel2.setVisible(true);
    }//GEN-LAST:event_bmLabel_AddCustomerMouseEntered

    private void bmLabel_AddCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_AddCustomerMouseExited
        jLabel2.setVisible(false);
    }//GEN-LAST:event_bmLabel_AddCustomerMouseExited

    private void bmLabel_SearchCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_SearchCustomerMouseEntered
        jLabel1.setVisible(true);
    }//GEN-LAST:event_bmLabel_SearchCustomerMouseEntered

    private void bmLabel_SearchCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_SearchCustomerMouseExited
        jLabel1.setVisible(false);
    }//GEN-LAST:event_bmLabel_SearchCustomerMouseExited

    private void bmLabel_DeleteCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_DeleteCustomerMouseEntered
        jLabel3.setVisible(true);
    }//GEN-LAST:event_bmLabel_DeleteCustomerMouseEntered

    private void bmLabel_DeleteCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_DeleteCustomerMouseExited
        jLabel3.setVisible(false);
    }//GEN-LAST:event_bmLabel_DeleteCustomerMouseExited

    private void bmLabel_UpdateCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_UpdateCustomerMouseEntered
        jLabel4.setVisible(true);
    }//GEN-LAST:event_bmLabel_UpdateCustomerMouseEntered

    private void bmLabel_UpdateCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmLabel_UpdateCustomerMouseExited
        jLabel4.setVisible(false);
    }//GEN-LAST:event_bmLabel_UpdateCustomerMouseExited

    private void minimizeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonLabelMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeButtonLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrandManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLable;
    private javax.swing.JLabel bmAddLabelUpdateOrDelete;
    private javax.swing.JTable bmAddTabel_View;
    private javax.swing.JTextField bmAddText_CustomerId;
    private javax.swing.JTextField bmAddText_CustomerName;
    private javax.swing.JLabel bmLabel_AddCustomer;
    private javax.swing.JLabel bmLabel_DeleteCustomer;
    private javax.swing.JLabel bmLabel_SearchCustomer;
    private javax.swing.JLabel bmLabel_UpdateCustomer;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel closeButtonLabel;
    private javax.swing.JLabel cmAddLabel_CustId;
    private javax.swing.JLabel cmAddLabel_CustName;
    private javax.swing.JLabel cmAddLabel_Main;
    private javax.swing.JPanel cmAddPanel_GetDetail;
    private javax.swing.JPanel cmAddPanell_Main;
    private javax.swing.JPanel cmCustDetailPanel;
    private javax.swing.JPanel cmCustMaintaimPanel;
    private javax.swing.JPanel dateTimePanel;
    private javax.swing.JPanel homeIconPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainButtonPanel;
    private javax.swing.JLabel minimizeButtonLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

    private void getclock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    clock.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
//                        JOptionPane.showMessageDialog(RoomDetails.this, "Database Error...");
                    }
                }
            }
        }).start();
    }

    private void setClearAll() {
        bmAddText_CustomerId.setText("");
        bmAddText_CustomerName.setText("");

    }

    private void showAllCustomers() {
        try {
            ArrayList<Brand> allBrandList = BrandController.showFromBrandTable();
            DefaultTableModel defaultTableModel = (DefaultTableModel) bmAddTabel_View.getModel();
            defaultTableModel.setRowCount(0);
            for (Brand brand : allBrandList) {
                Object[] rowData = {brand.getBrandId(), brand.getBrandName()};
                defaultTableModel.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchBrand() {

        try {
            String brandId = JOptionPane.showInputDialog(this, "Enter BrandID First...");
            Brand brand = BrandController.getFromBrandTable(brandId);
            if (brand != null) {
                bmAddText_CustomerId.setText(brandId);
                bmAddText_CustomerName.setText(brand.getBrandName());

            } else {
                JOptionPane.showMessageDialog(this, "No Brand Found in " + brandId + " BrandID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void modifyInBrandTable() {
        try {
            String brandId = bmAddText_CustomerId.getText();
            String brandName = bmAddText_CustomerName.getText();

            Brand brand = new Brand(brandId, brandName);
            boolean updateOrNot = BrandController.modifyinBrandTable(brand);
            if (updateOrNot) {
                JOptionPane.showMessageDialog(this, "Brand Update Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Can't Update Brand.. Please Check Your Details");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeFromBrandTable() {
        String brandId = bmAddText_CustomerId.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure??");
        if (confirm == 0) {
            try {
                boolean deleteOrNot = BrandController.removeFromBrandTable(brandId);
                if (deleteOrNot) {
                    JOptionPane.showMessageDialog(this, "Delete Brand Successfully..");
                }
            } catch (SQLException ex) {
                Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
                Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
                Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Customer Never Deleted..");
        }
    }

    private void intoBrandTable() {
        try {
            String brandId = bmAddText_CustomerId.getText();
            String brandName = bmAddText_CustomerName.getText();

            Brand brand = new Brand(brandId, brandName);
            boolean addOrNot = BrandController.intoBrandTable(brand);
            if (addOrNot) {
                JOptionPane.showMessageDialog(this, "Brand Added Successfully");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadBrandId() {
        try {
            String newId = IDGenerator.getNewID("Brand", "brandId", "I");
            bmAddText_CustomerId.setText(newId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BrandManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
