/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omicron.view;

import Others.IDGenerator;
import Others.ValidationController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeArray;
import omicron.controller.CustomerController;
import omicron.model.Customer;

/**
 *
 * @author Dulan
 */
public class CustomerManagement extends javax.swing.JFrame {

    int timeRun = 0;
    String customerNic;

    /**
     * Creates new form CustomerManagement
     */
    public CustomerManagement() {
        initComponents();
        getclock();
        cmAddLabelUpdateOrDelete.setVisible(false);
        showAllCustomers();
        cmAddLabelGoBack.setVisible(false);

        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        setCustomerId();
        cmAddText_CustomerId.setEditable(false);
    }

    CustomerManagement(String customerNic) {
        initComponents();
        getclock();
        cmAddLabelUpdateOrDelete.setText("Add");
        cmAddLabelUpdateOrDelete.setVisible(true);
        showAllCustomers();
        this.customerNic = customerNic;
        cmAddText_CustomerNIC.setText(customerNic);
        cmAddLabelGoBack.setVisible(true);

        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        setCustomerId();
        cmAddText_CustomerId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeIconPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mainButtonPanel = new javax.swing.JPanel();
        closeButtonLabel = new javax.swing.JLabel();
        minimizeButtonLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmAddTabel_View = new javax.swing.JTable();
        cmCustDetailPanel = new javax.swing.JPanel();
        cmAddPanell_Main = new javax.swing.JPanel();
        cmAddLabel_Main = new javax.swing.JLabel();
        cmAddPanel_GetDetail = new javax.swing.JPanel();
        cmAddLabel_CustId = new javax.swing.JLabel();
        cmAddText_CustomerId = new javax.swing.JTextField();
        cmAddLabel_CustName = new javax.swing.JLabel();
        cmAddText_CustomerName = new javax.swing.JTextField();
        cmAddText_CustomerNIC = new javax.swing.JTextField();
        cmAddLabel_CustNIC = new javax.swing.JLabel();
        cmAddLabel_CustAddress = new javax.swing.JLabel();
        cmAddText_CustomerTel_Num = new javax.swing.JTextField();
        cmAddLabel_CustTel_Num = new javax.swing.JLabel();
        cmAddLabelUpdateOrDelete = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cmAddText_CustomerAddress = new javax.swing.JTextArea();
        cmAddLabelGoBack = new javax.swing.JLabel();
        cmCustMaintaimPanel = new javax.swing.JPanel();
        cmLabel_AddCustomer = new javax.swing.JLabel();
        cmLabel_DeleteCustomer = new javax.swing.JLabel();
        cmLabel_SearchCustomer = new javax.swing.JLabel();
        cmLabel_UpdateCustomer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateTimePanel = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        homeLabel = new javax.swing.JLabel();
        MainLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeIconPanel.setOpaque(false);

        javax.swing.GroupLayout homeIconPanelLayout = new javax.swing.GroupLayout(homeIconPanel);
        homeIconPanel.setLayout(homeIconPanelLayout);
        homeIconPanelLayout.setHorizontalGroup(
            homeIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        homeIconPanelLayout.setVerticalGroup(
            homeIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(homeIconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 610));

        titlePanel.setOpaque(false);

        titleLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setText("Customer Management...");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 510, 50));

        mainButtonPanel.setOpaque(false);

        closeButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omicron.images/close_64.png"))); // NOI18N
        closeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseClicked(evt);
            }
        });

        minimizeButtonLabel.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\minimize_64.png")); // NOI18N
        minimizeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainButtonPanelLayout = new javax.swing.GroupLayout(mainButtonPanel);
        mainButtonPanel.setLayout(mainButtonPanelLayout);
        mainButtonPanelLayout.setHorizontalGroup(
            mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainButtonPanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(minimizeButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainButtonPanelLayout.setVerticalGroup(
            mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainButtonPanelLayout.createSequentialGroup()
                .addGroup(mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 130, -1));

        tablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), null, null));
        tablePanel.setOpaque(false);

        cmAddTabel_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerId", "Name", "NIC", "Address", "Tel_Num"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cmAddTabel_View.setOpaque(false);
        jScrollPane1.setViewportView(cmAddTabel_View);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        getContentPane().add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 660, 390));

        cmCustDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmCustDetailPanel.setOpaque(false);
        cmCustDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmAddPanell_Main.setBackground(new java.awt.Color(255, 0, 153));
        cmAddPanell_Main.setOpaque(false);

        cmAddLabel_Main.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        cmAddLabel_Main.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_Main.setText("Customer Details");

        javax.swing.GroupLayout cmAddPanell_MainLayout = new javax.swing.GroupLayout(cmAddPanell_Main);
        cmAddPanell_Main.setLayout(cmAddPanell_MainLayout);
        cmAddPanell_MainLayout.setHorizontalGroup(
            cmAddPanell_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanell_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmAddLabel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        cmAddPanell_MainLayout.setVerticalGroup(
            cmAddPanell_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmAddLabel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        cmCustDetailPanel.add(cmAddPanell_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        cmAddPanel_GetDetail.setOpaque(false);

        cmAddLabel_CustId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmAddLabel_CustId.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustId.setText("Customer ID");

        cmAddText_CustomerId.setBackground(new java.awt.Color(204, 204, 204));
        cmAddText_CustomerId.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmAddText_CustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAddText_CustomerIdActionPerformed(evt);
            }
        });

        cmAddLabel_CustName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmAddLabel_CustName.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustName.setText("Customer Name");

        cmAddText_CustomerName.setBackground(new java.awt.Color(204, 204, 204));
        cmAddText_CustomerName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmAddText_CustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAddText_CustomerNameActionPerformed(evt);
            }
        });
        cmAddText_CustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerNameKeyReleased(evt);
            }
        });

        cmAddText_CustomerNIC.setBackground(new java.awt.Color(204, 204, 204));
        cmAddText_CustomerNIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmAddText_CustomerNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAddText_CustomerNICActionPerformed(evt);
            }
        });
        cmAddText_CustomerNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerNICKeyReleased(evt);
            }
        });

        cmAddLabel_CustNIC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmAddLabel_CustNIC.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustNIC.setText("Customer NIC");

        cmAddLabel_CustAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmAddLabel_CustAddress.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustAddress.setText("Address");

        cmAddText_CustomerTel_Num.setBackground(new java.awt.Color(204, 204, 204));
        cmAddText_CustomerTel_Num.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmAddText_CustomerTel_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAddText_CustomerTel_NumActionPerformed(evt);
            }
        });
        cmAddText_CustomerTel_Num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerTel_NumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerTel_NumKeyReleased(evt);
            }
        });

        cmAddLabel_CustTel_Num.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmAddLabel_CustTel_Num.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_CustTel_Num.setText("Tel Num");

        cmAddLabelUpdateOrDelete.setBackground(new java.awt.Color(0, 165, 255));
        cmAddLabelUpdateOrDelete.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        cmAddLabelUpdateOrDelete.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabelUpdateOrDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmAddLabelUpdateOrDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmAddLabelUpdateOrDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmAddLabelUpdateOrDeleteMouseClicked(evt);
            }
        });

        cmAddText_CustomerAddress.setBackground(new java.awt.Color(204, 204, 204));
        cmAddText_CustomerAddress.setColumns(20);
        cmAddText_CustomerAddress.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmAddText_CustomerAddress.setRows(5);
        cmAddText_CustomerAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmAddText_CustomerAddressKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(cmAddText_CustomerAddress);

        cmAddLabelGoBack.setBackground(new java.awt.Color(0, 165, 255));
        cmAddLabelGoBack.setFont(new java.awt.Font("Sylfaen", 3, 21)); // NOI18N
        cmAddLabelGoBack.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabelGoBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmAddLabelGoBack.setText("<< Go Back");
        cmAddLabelGoBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmAddLabelGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmAddLabelGoBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cmAddPanel_GetDetailLayout = new javax.swing.GroupLayout(cmAddPanel_GetDetail);
        cmAddPanel_GetDetail.setLayout(cmAddPanel_GetDetailLayout);
        cmAddPanel_GetDetailLayout.setHorizontalGroup(
            cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addComponent(cmAddLabel_CustId, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmAddText_CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addComponent(cmAddLabel_CustNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmAddText_CustomerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addComponent(cmAddLabel_CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmAddText_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addComponent(cmAddLabel_CustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                            .addComponent(cmAddLabelGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmAddLabelUpdateOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                            .addComponent(cmAddLabel_CustTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmAddText_CustomerTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        cmAddPanel_GetDetailLayout.setVerticalGroup(
            cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmAddText_CustomerId, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cmAddLabel_CustId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmAddText_CustomerName)
                    .addComponent(cmAddLabel_CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmAddText_CustomerNIC)
                    .addComponent(cmAddLabel_CustNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmAddLabel_CustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmAddText_CustomerTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmAddLabel_CustTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmAddLabelUpdateOrDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(cmAddLabelGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        cmCustDetailPanel.add(cmAddPanel_GetDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 490));

        getContentPane().add(cmCustDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 470, 560));

        cmCustMaintaimPanel.setOpaque(false);

        cmLabel_AddCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custAdd.png")); // NOI18N
        cmLabel_AddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmLabel_AddCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmLabel_AddCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmLabel_AddCustomerMouseExited(evt);
            }
        });

        cmLabel_DeleteCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custDelete.png")); // NOI18N
        cmLabel_DeleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmLabel_DeleteCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmLabel_DeleteCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmLabel_DeleteCustomerMouseExited(evt);
            }
        });

        cmLabel_SearchCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custSearch.png")); // NOI18N
        cmLabel_SearchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmLabel_SearchCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmLabel_SearchCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmLabel_SearchCustomerMouseExited(evt);
            }
        });

        cmLabel_UpdateCustomer.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custUpdate.png")); // NOI18N
        cmLabel_UpdateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmLabel_UpdateCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmLabel_UpdateCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmLabel_UpdateCustomerMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delete");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout cmCustMaintaimPanelLayout = new javax.swing.GroupLayout(cmCustMaintaimPanel);
        cmCustMaintaimPanel.setLayout(cmCustMaintaimPanelLayout);
        cmCustMaintaimPanelLayout.setHorizontalGroup(
            cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addGroup(cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmLabel_AddCustomer)
                    .addComponent(cmLabel_DeleteCustomer)
                    .addComponent(cmLabel_SearchCustomer)
                    .addComponent(cmLabel_UpdateCustomer)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cmCustMaintaimPanelLayout.setVerticalGroup(
            cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addComponent(cmLabel_AddCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(cmLabel_SearchCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(cmLabel_DeleteCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(cmLabel_UpdateCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        getContentPane().add(cmCustMaintaimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 180, 80, 550));

        dateTimePanel.setOpaque(false);

        clock.setFont(new java.awt.Font("DS-Digital", 0, 60)); // NOI18N
        clock.setForeground(new java.awt.Color(0, 165, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clock.setText("2:13:15  PM");

        javax.swing.GroupLayout dateTimePanelLayout = new javax.swing.GroupLayout(dateTimePanel);
        dateTimePanel.setLayout(dateTimePanelLayout);
        dateTimePanelLayout.setHorizontalGroup(
            dateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateTimePanelLayout.createSequentialGroup()
                .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        dateTimePanelLayout.setVerticalGroup(
            dateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(dateTimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 310, 60));

        jButton1.setFont(new java.awt.Font("Miriam Fixed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 690, 140, 40));

        homeLabel.setFont(new java.awt.Font("Lucida Bright", 3, 85)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 205, 200));
        homeLabel.setText("  O");
        getContentPane().add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 110));

        MainLable.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\final.jpg")); // NOI18N
        MainLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(MainLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonLabelMouseClicked

    private void cmAddText_CustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmAddText_CustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmAddText_CustomerIdActionPerformed

    private void cmAddText_CustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmAddText_CustomerNameActionPerformed
        cmAddText_CustomerNIC.requestFocus();
    }//GEN-LAST:event_cmAddText_CustomerNameActionPerformed

    private void cmAddText_CustomerNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmAddText_CustomerNICActionPerformed
        ValidationController.checkNic(cmAddText_CustomerNIC, cmAddText_CustomerAddress);
    }//GEN-LAST:event_cmAddText_CustomerNICActionPerformed

    private void cmAddText_CustomerTel_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmAddText_CustomerTel_NumActionPerformed
        ValidationController.validateTel(cmAddText_CustomerTel_Num);
    }//GEN-LAST:event_cmAddText_CustomerTel_NumActionPerformed

    private void cmLabel_AddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_AddCustomerMouseClicked
        setClearAll();
        cmAddLabelUpdateOrDelete.setText("Add");
        cmAddLabelUpdateOrDelete.setVisible(true);
        setCustomerId();
    }//GEN-LAST:event_cmLabel_AddCustomerMouseClicked

    private void cmLabel_SearchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_SearchCustomerMouseClicked
        setClearAll();
        cmAddLabelUpdateOrDelete.setText("OK");
        cmAddLabelUpdateOrDelete.setVisible(true);
        searchCustomer();
    }//GEN-LAST:event_cmLabel_SearchCustomerMouseClicked

    private void cmLabel_UpdateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_UpdateCustomerMouseClicked
        setClearAll();
        cmAddLabelUpdateOrDelete.setText("Update");
        cmAddLabelUpdateOrDelete.setVisible(true);

        searchCustomer();
    }//GEN-LAST:event_cmLabel_UpdateCustomerMouseClicked

    private void cmLabel_DeleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_DeleteCustomerMouseClicked
        setClearAll();
        cmAddLabelUpdateOrDelete.setText("Delete");
        cmAddLabelUpdateOrDelete.setVisible(true);
        searchCustomer();

    }//GEN-LAST:event_cmLabel_DeleteCustomerMouseClicked

    private void cmAddLabelUpdateOrDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmAddLabelUpdateOrDeleteMouseClicked
        String text = cmAddLabelUpdateOrDelete.getText();
//        setCustomerId();
        if (text.equals("Update")) {
            modifyInCustomerTable();
        } else if (text.equals("Delete")) {
            removeFromCustomerTable();
        } else if (text.equals("Add")) {
            intoCustomerTable();
        }
        setClearAll();
        showAllCustomers();
        setCustomerId();
    }//GEN-LAST:event_cmAddLabelUpdateOrDeleteMouseClicked

    private void cmAddLabelGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmAddLabelGoBackMouseClicked
//        new OrderManagement(customerNic).setVisible(true);

        //frame.setVisible(false);
        this.dispose();
//        setDefaultCloseOperation(CustomerManagement.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_cmAddLabelGoBackMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmLabel_AddCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_AddCustomerMouseEntered
        jLabel2.setVisible(true);
    }//GEN-LAST:event_cmLabel_AddCustomerMouseEntered

    private void cmLabel_AddCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_AddCustomerMouseExited
        jLabel2.setVisible(false);
    }//GEN-LAST:event_cmLabel_AddCustomerMouseExited

    private void cmLabel_SearchCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_SearchCustomerMouseEntered
        jLabel1.setVisible(true);
    }//GEN-LAST:event_cmLabel_SearchCustomerMouseEntered

    private void cmLabel_SearchCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_SearchCustomerMouseExited
        jLabel1.setVisible(false);
    }//GEN-LAST:event_cmLabel_SearchCustomerMouseExited

    private void cmLabel_DeleteCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_DeleteCustomerMouseEntered
        jLabel3.setVisible(true);
    }//GEN-LAST:event_cmLabel_DeleteCustomerMouseEntered

    private void cmLabel_DeleteCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_DeleteCustomerMouseExited
        jLabel3.setVisible(false);
    }//GEN-LAST:event_cmLabel_DeleteCustomerMouseExited

    private void cmLabel_UpdateCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_UpdateCustomerMouseEntered
        jLabel4.setVisible(true);
    }//GEN-LAST:event_cmLabel_UpdateCustomerMouseEntered

    private void cmLabel_UpdateCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmLabel_UpdateCustomerMouseExited
        jLabel4.setVisible(false);
    }//GEN-LAST:event_cmLabel_UpdateCustomerMouseExited

    private void cmAddText_CustomerNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerNICKeyPressed
//        ValidationController.checkNicNumberCount(cmAddText_CustomerNIC);
    }//GEN-LAST:event_cmAddText_CustomerNICKeyPressed

    private void cmAddText_CustomerNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerNICKeyReleased
//        ValidationController.checkNicNumberCount(cmAddText_CustomerNIC);
    }//GEN-LAST:event_cmAddText_CustomerNICKeyReleased

    private void cmAddText_CustomerAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmAddText_CustomerTel_Num.requestFocus();
        }
    }//GEN-LAST:event_cmAddText_CustomerAddressKeyPressed

    private void cmAddText_CustomerTel_NumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerTel_NumKeyPressed
        ValidationController.numberOnly(cmAddText_CustomerTel_Num);
    }//GEN-LAST:event_cmAddText_CustomerTel_NumKeyPressed

    private void cmAddText_CustomerTel_NumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerTel_NumKeyReleased
        ValidationController.numberOnly(cmAddText_CustomerTel_Num);
    }//GEN-LAST:event_cmAddText_CustomerTel_NumKeyReleased

    private void cmAddText_CustomerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerNameKeyPressed
        ValidationController.name(cmAddText_CustomerName);
    }//GEN-LAST:event_cmAddText_CustomerNameKeyPressed

    private void cmAddText_CustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmAddText_CustomerNameKeyReleased
        ValidationController.name(cmAddText_CustomerName);
    }//GEN-LAST:event_cmAddText_CustomerNameKeyReleased

    private void minimizeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonLabelMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeButtonLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLable;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel closeButtonLabel;
    private javax.swing.JLabel cmAddLabelGoBack;
    private javax.swing.JLabel cmAddLabelUpdateOrDelete;
    private javax.swing.JLabel cmAddLabel_CustAddress;
    private javax.swing.JLabel cmAddLabel_CustId;
    private javax.swing.JLabel cmAddLabel_CustNIC;
    private javax.swing.JLabel cmAddLabel_CustName;
    private javax.swing.JLabel cmAddLabel_CustTel_Num;
    private javax.swing.JLabel cmAddLabel_Main;
    private javax.swing.JPanel cmAddPanel_GetDetail;
    private javax.swing.JPanel cmAddPanell_Main;
    private javax.swing.JTable cmAddTabel_View;
    private javax.swing.JTextArea cmAddText_CustomerAddress;
    private javax.swing.JTextField cmAddText_CustomerId;
    private javax.swing.JTextField cmAddText_CustomerNIC;
    private javax.swing.JTextField cmAddText_CustomerName;
    private javax.swing.JTextField cmAddText_CustomerTel_Num;
    private javax.swing.JPanel cmCustDetailPanel;
    private javax.swing.JPanel cmCustMaintaimPanel;
    private javax.swing.JLabel cmLabel_AddCustomer;
    private javax.swing.JLabel cmLabel_DeleteCustomer;
    private javax.swing.JLabel cmLabel_SearchCustomer;
    private javax.swing.JLabel cmLabel_UpdateCustomer;
    private javax.swing.JPanel dateTimePanel;
    private javax.swing.JPanel homeIconPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainButtonPanel;
    private javax.swing.JLabel minimizeButtonLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

    private void getclock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    clock.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
//                        JOptionPane.showMessageDialog(RoomDetails.this, "Database Error...");
                    }
                }
            }
        }).start();
    }

    private void setClearAll() {
        cmAddText_CustomerId.setText("");
        cmAddText_CustomerName.setText("");
        cmAddText_CustomerAddress.setText("");
        cmAddText_CustomerNIC.setText("");
        cmAddText_CustomerTel_Num.setText("");
    }

    private void showAllCustomers() {
        try {
            ArrayList<Customer> allCustomerList = CustomerController.showFromCustomerTable();
            DefaultTableModel defaultTableModel = (DefaultTableModel) cmAddTabel_View.getModel();
            defaultTableModel.setRowCount(0);
            for (Customer customer : allCustomerList) {
                Object[] rowData = {customer.getCustomerId(), customer.getCustomerName(), customer.getCustomerNic(), customer.getCustomerAddress(), customer.getCustomerTel_Num()};
                defaultTableModel.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchCustomer() {
        try {
            String customerId = JOptionPane.showInputDialog(this, "Enter CustomerID First...");
            Customer customer = CustomerController.getFromCustomerTable(customerId);
            if (customer != null) {
                cmAddText_CustomerId.setText(customerId);
                cmAddText_CustomerName.setText(customer.getCustomerName());
                cmAddText_CustomerAddress.setText(customer.getCustomerAddress());
                cmAddText_CustomerNIC.setText(customer.getCustomerNic());
                cmAddText_CustomerTel_Num.setText(Integer.toString(customer.getCustomerTel_Num()));
            } else {
                JOptionPane.showMessageDialog(this, "No Customer Found in " + customerId + " CustomerID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void modifyInCustomerTable() {
        try {
            String customerId = cmAddText_CustomerId.getText();
            String customerName = cmAddText_CustomerName.getText();
            String customerNic = cmAddText_CustomerNIC.getText();
            String customerAddress = cmAddText_CustomerAddress.getText();
            int customerTel_Num = Integer.parseInt(cmAddText_CustomerTel_Num.getText());

            Customer customer = new Customer(customerId, customerName, customerNic, customerAddress, customerTel_Num);
            boolean updateOrNot = CustomerController.modifyinCustomerTable(customer);
            if (updateOrNot) {
                JOptionPane.showMessageDialog(this, "Customer Update Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Can't Update Customer.. Please Check Your Details");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeFromCustomerTable() {
        String customerId = cmAddText_CustomerId.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure??");
        if (confirm == 0) {
            try {
                boolean deleteOrNot = CustomerController.removeFromCustomerTable(customerId);
                if (deleteOrNot) {
                    JOptionPane.showMessageDialog(this, "Delete Customer Successfully..");
                }
            } catch (SQLException ex) {
                Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
            JOptionPane.showMessageDialog(this, "Customer Never Deleted..");
        }
    }

    private void intoCustomerTable() {
        try {
            String customerId = cmAddText_CustomerId.getText();
            String customerName = cmAddText_CustomerName.getText();
            String customerNic = cmAddText_CustomerNIC.getText();
            String customerAddress = cmAddText_CustomerAddress.getText();
            int customerTel_Num = Integer.parseInt(cmAddText_CustomerTel_Num.getText());

            Customer customer = new Customer(customerId, customerName, customerNic, customerAddress, customerTel_Num);
            boolean addOrNot = CustomerController.intoCustomerTable(customer);
            if (addOrNot) {
                JOptionPane.showMessageDialog(this, "Customer Added Successfully");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCustomerId() {
        try {
            String newId = IDGenerator.getNewID("Customer", "customerId", "C");
            cmAddText_CustomerId.setText(newId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
