/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omicron.view;

import Others.IDGenerator;
import Others.ValidationController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import omicron.controller.CustomerController;
import omicron.controller.SupplierController;
import omicron.model.Customer;
import omicron.model.Supplier;
import omicron.model.Supply_Order;

/**
 *
 * @author Dulan
 */
public class SupplierManagement extends javax.swing.JFrame {

    int timeRun = 0;
    Supply_Order orderDetails;

    /**
     * Creates new form CustomerManagement
     */
    public SupplierManagement() {
        initComponents();
        getclock();
        showAllCustomers();
        smAddLabeGoBack.setVisible(false);
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        smAddText_SupplierId.setEditable(false);
        setSupplierId();
    }

    SupplierManagement(Supply_Order orderDetails) {
        initComponents();
        getclock();
        showAllCustomers();
        this.orderDetails = orderDetails;
        smAddLabelUpdateOrDelete.setText("Add");
        smAddLabelUpdateOrDelete.setVisible(true);
        smAddLabeGoBack.setVisible(true);
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        smAddText_SupplierId.setEditable(false);
        setSupplierId();
    }

    SupplierManagement(String SupplierNic) {
        initComponents();
        getclock();
        showAllCustomers();
        smAddLabelUpdateOrDelete.setText("Add");
        smAddLabelUpdateOrDelete.setVisible(true);
        smAddLabeGoBack.setVisible(true);
        smAddText_SupplierNIC.setText(SupplierNic);
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        smAddText_SupplierId.setEditable(false);
        setSupplierId();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        homeIconPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mainButtonPanel = new javax.swing.JPanel();
        closeButtonLabel = new javax.swing.JLabel();
        minimizeButtonLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        smAddTabel_View = new javax.swing.JTable();
        cmCustDetailPanel = new javax.swing.JPanel();
        cmAddPanell_Main = new javax.swing.JPanel();
        cmAddLabel_Main = new javax.swing.JLabel();
        cmAddPanel_GetDetail = new javax.swing.JPanel();
        smAddLabel_SuptId = new javax.swing.JLabel();
        smAddText_SupplierId = new javax.swing.JTextField();
        smAddLabel_SupName = new javax.swing.JLabel();
        smAddText_SupplierName = new javax.swing.JTextField();
        smAddText_SupplierNIC = new javax.swing.JTextField();
        smAddLabel_SupNIC = new javax.swing.JLabel();
        smAddLabel_SupAddress = new javax.swing.JLabel();
        smAddText_SupplierTel_Num = new javax.swing.JTextField();
        smAddLabel_SupTel_Num = new javax.swing.JLabel();
        smAddLabel_SupEmail = new javax.swing.JLabel();
        smAddText_SupplierEmail = new javax.swing.JTextField();
        smAddLabel_SupFax = new javax.swing.JLabel();
        smAddText_SupplierFax = new javax.swing.JTextField();
        smAddLabelUpdateOrDelete = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        smAddText_SupplierAddress = new javax.swing.JTextArea();
        smAddLabeGoBack = new javax.swing.JLabel();
        dateTimePanel = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        cmCustMaintaimPanel = new javax.swing.JPanel();
        smLabel_AddSupplier = new javax.swing.JLabel();
        smLabel_DeleteSupplier = new javax.swing.JLabel();
        smLabel_SearchSupplier = new javax.swing.JLabel();
        smLabel_UpdateSupplier = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MainLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setOpaque(false);

        homeLabel.setFont(new java.awt.Font("Lucida Bright", 3, 85)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 205, 200));
        homeLabel.setText("  O");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 130));

        homeIconPanel.setOpaque(false);

        javax.swing.GroupLayout homeIconPanelLayout = new javax.swing.GroupLayout(homeIconPanel);
        homeIconPanel.setLayout(homeIconPanelLayout);
        homeIconPanelLayout.setHorizontalGroup(
            homeIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        homeIconPanelLayout.setVerticalGroup(
            homeIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(homeIconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 560));

        titlePanel.setOpaque(false);

        titleLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setText("Supplier Management...");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 510, 50));

        mainButtonPanel.setOpaque(false);

        closeButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omicron.images/close_64.png"))); // NOI18N
        closeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseClicked(evt);
            }
        });

        minimizeButtonLabel.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\minimize_64.png")); // NOI18N
        minimizeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainButtonPanelLayout = new javax.swing.GroupLayout(mainButtonPanel);
        mainButtonPanel.setLayout(mainButtonPanelLayout);
        mainButtonPanelLayout.setHorizontalGroup(
            mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainButtonPanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(minimizeButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainButtonPanelLayout.setVerticalGroup(
            mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainButtonPanelLayout.createSequentialGroup()
                .addGroup(mainButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 130, -1));

        tablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), null, null));
        tablePanel.setOpaque(false);

        smAddTabel_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SupplierId", "Name", "NIC", "Address", "Tel Num", "Email", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        smAddTabel_View.setOpaque(false);
        jScrollPane1.setViewportView(smAddTabel_View);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 680, 320));

        cmCustDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmCustDetailPanel.setOpaque(false);
        cmCustDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmAddPanell_Main.setBackground(new java.awt.Color(255, 0, 153));
        cmAddPanell_Main.setOpaque(false);

        cmAddLabel_Main.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        cmAddLabel_Main.setForeground(new java.awt.Color(255, 255, 255));
        cmAddLabel_Main.setText("Supplier Details");

        javax.swing.GroupLayout cmAddPanell_MainLayout = new javax.swing.GroupLayout(cmAddPanell_Main);
        cmAddPanell_Main.setLayout(cmAddPanell_MainLayout);
        cmAddPanell_MainLayout.setHorizontalGroup(
            cmAddPanell_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanell_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmAddLabel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        cmAddPanell_MainLayout.setVerticalGroup(
            cmAddPanell_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmAddLabel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        cmCustDetailPanel.add(cmAddPanell_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        cmAddPanel_GetDetail.setOpaque(false);

        smAddLabel_SuptId.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SuptId.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SuptId.setText("Supplier ID");

        smAddText_SupplierId.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAddText_SupplierIdActionPerformed(evt);
            }
        });

        smAddLabel_SupName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SupName.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SupName.setText("Supplier Name");
        smAddLabel_SupName.setMaximumSize(new java.awt.Dimension(134, 29));
        smAddLabel_SupName.setMinimumSize(new java.awt.Dimension(134, 29));

        smAddText_SupplierName.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAddText_SupplierNameActionPerformed(evt);
            }
        });
        smAddText_SupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                smAddText_SupplierNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                smAddText_SupplierNameKeyReleased(evt);
            }
        });

        smAddText_SupplierNIC.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAddText_SupplierNICActionPerformed(evt);
            }
        });

        smAddLabel_SupNIC.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SupNIC.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SupNIC.setText("Supplier NIC");
        smAddLabel_SupNIC.setMaximumSize(new java.awt.Dimension(134, 29));
        smAddLabel_SupNIC.setMinimumSize(new java.awt.Dimension(134, 29));

        smAddLabel_SupAddress.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SupAddress.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SupAddress.setText("Address");
        smAddLabel_SupAddress.setMaximumSize(new java.awt.Dimension(134, 29));
        smAddLabel_SupAddress.setMinimumSize(new java.awt.Dimension(134, 29));

        smAddText_SupplierTel_Num.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierTel_Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierTel_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAddText_SupplierTel_NumActionPerformed(evt);
            }
        });
        smAddText_SupplierTel_Num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                smAddText_SupplierTel_NumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                smAddText_SupplierTel_NumKeyReleased(evt);
            }
        });

        smAddLabel_SupTel_Num.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SupTel_Num.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SupTel_Num.setText("Tel Num");
        smAddLabel_SupTel_Num.setMaximumSize(new java.awt.Dimension(134, 29));
        smAddLabel_SupTel_Num.setMinimumSize(new java.awt.Dimension(134, 29));

        smAddLabel_SupEmail.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SupEmail.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SupEmail.setText("Email");
        smAddLabel_SupEmail.setMaximumSize(new java.awt.Dimension(134, 29));
        smAddLabel_SupEmail.setMinimumSize(new java.awt.Dimension(134, 29));

        smAddText_SupplierEmail.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAddText_SupplierEmailActionPerformed(evt);
            }
        });
        smAddText_SupplierEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                smAddText_SupplierEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                smAddText_SupplierEmailKeyReleased(evt);
            }
        });

        smAddLabel_SupFax.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        smAddLabel_SupFax.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabel_SupFax.setText("Email ");
        smAddLabel_SupFax.setMaximumSize(new java.awt.Dimension(134, 29));
        smAddLabel_SupFax.setMinimumSize(new java.awt.Dimension(134, 29));

        smAddText_SupplierFax.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierFax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAddText_SupplierFaxActionPerformed(evt);
            }
        });

        smAddLabelUpdateOrDelete.setBackground(new java.awt.Color(0, 165, 255));
        smAddLabelUpdateOrDelete.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        smAddLabelUpdateOrDelete.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabelUpdateOrDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smAddLabelUpdateOrDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        smAddLabelUpdateOrDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smAddLabelUpdateOrDeleteMouseClicked(evt);
            }
        });

        smAddText_SupplierAddress.setBackground(new java.awt.Color(204, 204, 204));
        smAddText_SupplierAddress.setColumns(20);
        smAddText_SupplierAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        smAddText_SupplierAddress.setRows(5);
        smAddText_SupplierAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                smAddText_SupplierAddressKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(smAddText_SupplierAddress);

        smAddLabeGoBack.setBackground(new java.awt.Color(0, 165, 255));
        smAddLabeGoBack.setFont(new java.awt.Font("Sylfaen", 3, 21)); // NOI18N
        smAddLabeGoBack.setForeground(new java.awt.Color(255, 255, 255));
        smAddLabeGoBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smAddLabeGoBack.setText("<<Go Back");
        smAddLabeGoBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        smAddLabeGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smAddLabeGoBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cmAddPanel_GetDetailLayout = new javax.swing.GroupLayout(cmAddPanel_GetDetail);
        cmAddPanel_GetDetail.setLayout(cmAddPanel_GetDetailLayout);
        cmAddPanel_GetDetailLayout.setHorizontalGroup(
            cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smAddLabel_SupAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SuptId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupFax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smAddText_SupplierEmail)
                            .addComponent(smAddText_SupplierFax)
                            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(smAddText_SupplierNIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(smAddText_SupplierId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smAddText_SupplierName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(smAddText_SupplierTel_Num)))
                    .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(smAddLabeGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(smAddLabelUpdateOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        cmAddPanel_GetDetailLayout.setVerticalGroup(
            cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmAddPanel_GetDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smAddText_SupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SuptId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(smAddText_SupplierName)
                    .addComponent(smAddLabel_SupName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(smAddText_SupplierNIC)
                    .addComponent(smAddLabel_SupNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smAddLabel_SupAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smAddText_SupplierTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupTel_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smAddText_SupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smAddText_SupplierFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabel_SupFax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(cmAddPanel_GetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smAddLabelUpdateOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smAddLabeGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        cmCustDetailPanel.add(cmAddPanel_GetDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 510));

        getContentPane().add(cmCustDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 470, 580));

        dateTimePanel.setOpaque(false);

        clock.setFont(new java.awt.Font("DS-Digital", 0, 60)); // NOI18N
        clock.setForeground(new java.awt.Color(0, 165, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clock.setText("2:13:15  PM");

        javax.swing.GroupLayout dateTimePanelLayout = new javax.swing.GroupLayout(dateTimePanel);
        dateTimePanel.setLayout(dateTimePanelLayout);
        dateTimePanelLayout.setHorizontalGroup(
            dateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateTimePanelLayout.createSequentialGroup()
                .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        dateTimePanelLayout.setVerticalGroup(
            dateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(dateTimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 310, 60));

        cmCustMaintaimPanel.setOpaque(false);

        smLabel_AddSupplier.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custAdd.png")); // NOI18N
        smLabel_AddSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smLabel_AddSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                smLabel_AddSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                smLabel_AddSupplierMouseExited(evt);
            }
        });

        smLabel_DeleteSupplier.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custDelete.png")); // NOI18N
        smLabel_DeleteSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smLabel_DeleteSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                smLabel_DeleteSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                smLabel_DeleteSupplierMouseExited(evt);
            }
        });

        smLabel_SearchSupplier.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custSearch.png")); // NOI18N
        smLabel_SearchSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smLabel_SearchSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                smLabel_SearchSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                smLabel_SearchSupplierMouseExited(evt);
            }
        });

        smLabel_UpdateSupplier.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\custUpdate.png")); // NOI18N
        smLabel_UpdateSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smLabel_UpdateSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                smLabel_UpdateSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                smLabel_UpdateSupplierMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delete");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout cmCustMaintaimPanelLayout = new javax.swing.GroupLayout(cmCustMaintaimPanel);
        cmCustMaintaimPanel.setLayout(cmCustMaintaimPanelLayout);
        cmCustMaintaimPanelLayout.setHorizontalGroup(
            cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addGroup(cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smLabel_AddSupplier)
                    .addComponent(smLabel_DeleteSupplier)
                    .addComponent(smLabel_SearchSupplier)
                    .addComponent(smLabel_UpdateSupplier)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cmCustMaintaimPanelLayout.setVerticalGroup(
            cmCustMaintaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCustMaintaimPanelLayout.createSequentialGroup()
                .addComponent(smLabel_AddSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(smLabel_SearchSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(smLabel_DeleteSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(smLabel_UpdateSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(cmCustMaintaimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 190, 80, 530));

        jButton1.setFont(new java.awt.Font("Miriam Fixed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 690, 140, 40));

        MainLable.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\First Sem Project\\Omicron\\Omicron\\Omicron_Electronics\\src\\omicron.images\\final.jpg")); // NOI18N
        MainLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(MainLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonLabelMouseClicked

    private void smAddText_SupplierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAddText_SupplierIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smAddText_SupplierIdActionPerformed

    private void smAddText_SupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAddText_SupplierNameActionPerformed
        smAddText_SupplierNIC.requestFocus();
    }//GEN-LAST:event_smAddText_SupplierNameActionPerformed

    private void smAddText_SupplierNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAddText_SupplierNICActionPerformed
        ValidationController.checkNic(smAddText_SupplierNIC, smAddText_SupplierAddress);
    }//GEN-LAST:event_smAddText_SupplierNICActionPerformed

    private void smAddText_SupplierTel_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAddText_SupplierTel_NumActionPerformed
        boolean check = ValidationController.validateTel(smAddText_SupplierTel_Num);
        if (check) {
            smAddText_SupplierEmail.requestFocus();
        }

    }//GEN-LAST:event_smAddText_SupplierTel_NumActionPerformed

    private void smAddText_SupplierEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAddText_SupplierEmailActionPerformed
        String email = smAddText_SupplierEmail.getText();
        boolean isValid = ValidationController.isValidEmailAddress(email);
        if (isValid) {
            smAddText_SupplierFax.requestFocus();
        }
    }//GEN-LAST:event_smAddText_SupplierEmailActionPerformed

    private void smAddText_SupplierFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAddText_SupplierFaxActionPerformed
        String email = smAddText_SupplierEmail.getText();
        boolean isValid = ValidationController.isValidEmailAddress(email);
        if (isValid) {
            smAddLabelUpdateOrDelete.requestFocus();
        }
    }//GEN-LAST:event_smAddText_SupplierFaxActionPerformed

    private void smAddLabelUpdateOrDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smAddLabelUpdateOrDeleteMouseClicked
        String text = smAddLabelUpdateOrDelete.getText();
        if (text.equals("Update")) {
            modifyInSupplierTable();
        } else if (text.equals("Delete")) {
            removeFromSupplierTable();
        } else if (text.equals("Add")) {
            intoSupplierTable();
        }
        setClearAll();
        showAllCustomers();
        setSupplierId();
    }//GEN-LAST:event_smAddLabelUpdateOrDeleteMouseClicked

    private void smLabel_AddSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_AddSupplierMouseClicked
        setClearAll();
        setSupplierId();
        smAddLabelUpdateOrDelete.setText("Add");
        smAddLabelUpdateOrDelete.setVisible(true);
    }//GEN-LAST:event_smLabel_AddSupplierMouseClicked

    private void smLabel_DeleteSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_DeleteSupplierMouseClicked
        setClearAll();
        smAddLabelUpdateOrDelete.setText("Delete");
        smAddLabelUpdateOrDelete.setVisible(true);
        getFromSupplierTable();

    }//GEN-LAST:event_smLabel_DeleteSupplierMouseClicked

    private void smLabel_SearchSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_SearchSupplierMouseClicked
        setClearAll();
        smAddLabelUpdateOrDelete.setText("OK");
        smAddLabelUpdateOrDelete.setVisible(true);
        getFromSupplierTable();
    }//GEN-LAST:event_smLabel_SearchSupplierMouseClicked

    private void smLabel_UpdateSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_UpdateSupplierMouseClicked
        setClearAll();
        smAddLabelUpdateOrDelete.setText("Update");
        smAddLabelUpdateOrDelete.setVisible(true);
        getFromSupplierTable();
    }//GEN-LAST:event_smLabel_UpdateSupplierMouseClicked

    private void smAddLabeGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smAddLabeGoBackMouseClicked
        new SupplierOrderManagement(orderDetails).setVisible(true);

    }//GEN-LAST:event_smAddLabeGoBackMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void smLabel_AddSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_AddSupplierMouseEntered
        jLabel2.setVisible(true);
    }//GEN-LAST:event_smLabel_AddSupplierMouseEntered

    private void smLabel_AddSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_AddSupplierMouseExited
        jLabel2.setVisible(false);

    }//GEN-LAST:event_smLabel_AddSupplierMouseExited

    private void smLabel_SearchSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_SearchSupplierMouseEntered
        jLabel1.setVisible(true);
    }//GEN-LAST:event_smLabel_SearchSupplierMouseEntered

    private void smLabel_SearchSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_SearchSupplierMouseExited
        jLabel1.setVisible(false);
    }//GEN-LAST:event_smLabel_SearchSupplierMouseExited

    private void smLabel_DeleteSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_DeleteSupplierMouseEntered
        jLabel3.setVisible(true);
    }//GEN-LAST:event_smLabel_DeleteSupplierMouseEntered

    private void smLabel_DeleteSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_DeleteSupplierMouseExited
        jLabel3.setVisible(false);
    }//GEN-LAST:event_smLabel_DeleteSupplierMouseExited

    private void smLabel_UpdateSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_UpdateSupplierMouseEntered
        jLabel4.setVisible(true);
    }//GEN-LAST:event_smLabel_UpdateSupplierMouseEntered

    private void smLabel_UpdateSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLabel_UpdateSupplierMouseExited
        jLabel4.setVisible(false);
    }//GEN-LAST:event_smLabel_UpdateSupplierMouseExited

    private void smAddText_SupplierNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierNameKeyPressed
        ValidationController.name(smAddText_SupplierName);
    }//GEN-LAST:event_smAddText_SupplierNameKeyPressed

    private void smAddText_SupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierNameKeyReleased
        ValidationController.name(smAddText_SupplierName);
    }//GEN-LAST:event_smAddText_SupplierNameKeyReleased

    private void smAddText_SupplierAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            smAddText_SupplierTel_Num.requestFocus();
        }
    }//GEN-LAST:event_smAddText_SupplierAddressKeyPressed

    private void smAddText_SupplierTel_NumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierTel_NumKeyPressed
        ValidationController.numberOnly(smAddText_SupplierTel_Num);
    }//GEN-LAST:event_smAddText_SupplierTel_NumKeyPressed

    private void smAddText_SupplierTel_NumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierTel_NumKeyReleased
        ValidationController.numberOnly(smAddText_SupplierTel_Num);
    }//GEN-LAST:event_smAddText_SupplierTel_NumKeyReleased

    private void smAddText_SupplierEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierEmailKeyPressed
//        ValidationController.validationEmail(smAddText_SupplierEmail);
    }//GEN-LAST:event_smAddText_SupplierEmailKeyPressed

    private void smAddText_SupplierEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smAddText_SupplierEmailKeyReleased
//        ValidationController.validationEmail(smAddText_SupplierEmail);
    }//GEN-LAST:event_smAddText_SupplierEmailKeyReleased

    private void minimizeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonLabelMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeButtonLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLable;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel closeButtonLabel;
    private javax.swing.JLabel cmAddLabel_Main;
    private javax.swing.JPanel cmAddPanel_GetDetail;
    private javax.swing.JPanel cmAddPanell_Main;
    private javax.swing.JPanel cmCustDetailPanel;
    private javax.swing.JPanel cmCustMaintaimPanel;
    private javax.swing.JPanel dateTimePanel;
    private javax.swing.JPanel homeIconPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainButtonPanel;
    private javax.swing.JLabel minimizeButtonLabel;
    private javax.swing.JLabel smAddLabeGoBack;
    private javax.swing.JLabel smAddLabelUpdateOrDelete;
    private javax.swing.JLabel smAddLabel_SupAddress;
    private javax.swing.JLabel smAddLabel_SupEmail;
    private javax.swing.JLabel smAddLabel_SupFax;
    private javax.swing.JLabel smAddLabel_SupNIC;
    private javax.swing.JLabel smAddLabel_SupName;
    private javax.swing.JLabel smAddLabel_SupTel_Num;
    private javax.swing.JLabel smAddLabel_SuptId;
    private javax.swing.JTable smAddTabel_View;
    private javax.swing.JTextArea smAddText_SupplierAddress;
    private javax.swing.JTextField smAddText_SupplierEmail;
    private javax.swing.JTextField smAddText_SupplierFax;
    private javax.swing.JTextField smAddText_SupplierId;
    private javax.swing.JTextField smAddText_SupplierNIC;
    private javax.swing.JTextField smAddText_SupplierName;
    private javax.swing.JTextField smAddText_SupplierTel_Num;
    private javax.swing.JLabel smLabel_AddSupplier;
    private javax.swing.JLabel smLabel_DeleteSupplier;
    private javax.swing.JLabel smLabel_SearchSupplier;
    private javax.swing.JLabel smLabel_UpdateSupplier;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

    private void getclock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    clock.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
//                        JOptionPane.showMessageDialog(RoomDetails.this, "Database Error...");
                    }
                }
            }
        }).start();
    }

    private void setClearAll() {
        smAddText_SupplierId.setText("");
        smAddText_SupplierName.setText("");
        smAddText_SupplierNIC.setText("");

        smAddText_SupplierAddress.setText("");
        smAddText_SupplierTel_Num.setText("");
        smAddText_SupplierEmail.setText("");
        smAddText_SupplierFax.setText("");

    }

    private void showAllCustomers() {
        try {
            ArrayList<Supplier> allSupplierList = SupplierController.showFromSupplierTable();
            DefaultTableModel defaultTableModel = (DefaultTableModel) smAddTabel_View.getModel();
            defaultTableModel.setRowCount(0);
            for (Supplier supplier : allSupplierList) {
                Object[] rowData = {supplier.getSupplierId(), supplier.getSupplierName(), supplier.getSupplierNic(), supplier.getSupplierAddress(), supplier.getSupplierTel_Num(), supplier.getSupplierEmail(), supplier.getSupplierFax()};
                defaultTableModel.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getFromSupplierTable() {
        try {
            String supplierId = JOptionPane.showInputDialog(this, "Enter SupplierID First...");
            Supplier supplier = SupplierController.getFromSupplierTable(supplierId);
            if (supplier != null) {
                smAddText_SupplierId.setText(supplier.getSupplierId());
                smAddText_SupplierName.setText(supplier.getSupplierName());
                smAddText_SupplierNIC.setText(supplier.getSupplierNic());

                smAddText_SupplierAddress.setText(supplier.getSupplierAddress());
                smAddText_SupplierTel_Num.setText(Integer.toString(supplier.getSupplierTel_Num()));
                smAddText_SupplierEmail.setText(supplier.getSupplierEmail());
                smAddText_SupplierFax.setText(supplier.getSupplierFax());

            } else {
                JOptionPane.showMessageDialog(this, "No Supplier Found in " + supplierId + " SupplierID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void modifyInSupplierTable() {
        try {
            String supplierId = smAddText_SupplierId.getText();
            String supplierName = smAddText_SupplierName.getText();
            String supplierNic = smAddText_SupplierNIC.getText();

            String supplierAddress = smAddText_SupplierAddress.getText();
            int supplierTel_Num = Integer.parseInt(smAddText_SupplierTel_Num.getText());
            String supplierEmail = smAddText_SupplierEmail.getText();
            String supplierFax = smAddText_SupplierFax.getText();

            Supplier supplier = new Supplier(supplierId, supplierName, supplierNic, supplierAddress, supplierTel_Num, supplierEmail, supplierFax);
            boolean updateOrNot = SupplierController.modifyinSupplierTable(supplier);
            if (updateOrNot) {
                JOptionPane.showMessageDialog(this, "Customer Update Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Can't Update Customer.. Please Check Your Details");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeFromSupplierTable() {
        String supplierId = smAddText_SupplierId.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure??");
        if (confirm == 0) {
            try {
                boolean deleteOrNot = SupplierController.removeFromSupplierTable(supplierId);
                if (deleteOrNot) {
                    JOptionPane.showMessageDialog(this, "Delete Customer Successfully..");
                }
            } catch (SQLException ex) {
                Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
                Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
                Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Customer Never Deleted..");
        }
    }

    private void intoSupplierTable() {
        try {
            String supplierId = smAddText_SupplierId.getText();
            String supplierName = smAddText_SupplierName.getText();
            String supplierNic = smAddText_SupplierNIC.getText();

            String supplierAddress = smAddText_SupplierAddress.getText();
            int supplierTel_Num = Integer.parseInt(smAddText_SupplierTel_Num.getText());
            String supplierEmail = smAddText_SupplierEmail.getText();
            String supplierFax = smAddText_SupplierFax.getText();

            Supplier supplier = new Supplier(supplierId, supplierName, supplierNic, supplierAddress, supplierTel_Num, supplierEmail, supplierFax);
            boolean addOrNot = SupplierController.intoSupplierTable(supplier);
            if (addOrNot) {
                JOptionPane.showMessageDialog(this, "Supplier Added Successfully");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void setSupplierId() {
        try {
            String newSupplierId = IDGenerator.getNewID("Supplier", "supplierId", "S");
            smAddText_SupplierId.setText(newSupplierId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SupplierManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(GRNManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in your Inserted Data.. Please check again..");
            Logger.getLogger(DamageManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
